### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by bitFiedler**

### CODE REVIEW

**Comment by ilg-ul** [comment]
I take this as a request to make a new release. planned shortly.

**Comment by bitFiedler** [comment]
not really necessary, I pulled the develop branch and did some tests.
But the float to string formatting but is still there, or did I miss something. 

What I did not understand why I can’t step into the sprintf function to do the debugging, because I want to see why my system is crashing.

cheers,
matthias

**Comment by ilg-ul** [comment]
for the printf() fix you need to pull the -cortexm.git.

you cannot step into sprintf() because it is in newlib, and the library does not include debug info.

**Comment by ilg-ul** [comment]
and please do not reply by email to these messages.

**Comment by ilg-ul** [comment]
for the 'printf()' problems, see https://github.com/micro-os-plus/micro-os-plus-iii/issues/6

**Comment by bitFiedler** [comment]
Hi Livius,

Thanks for the Information, but now printf do not show any float/double value.
Good news is, the processor does not a hard fault any more.

cheers,
matthias

**Comment by ilg-ul** [comment]
can you be more specific? (and do not replay by email, use the github web interface)

**Comment by ilg-ul** [comment]
if you are using newlib-nano, did you explicitly enable float support?

**Comment by ilg-ul** [comment]
as for stepping into library functions, see

http://micro-os-plus.github.io/support/faq/

**Pull request merged**
